# Generated by Django 4.2.24 on 2025-11-09 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SplitwiseIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=500)),
                ("token_type", models.CharField(default="Bearer", max_length=50)),
                ("splitwise_user_id", models.IntegerField(blank=True, null=True)),
                (
                    "splitwise_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "splitwise_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "splitwise_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "auto_sync_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Automatically sync changes bi-directionally",
                    ),
                ),
                (
                    "sync_interval_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="How often to check for updates from Splitwise (in minutes)",
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("syncing", "Syncing"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        db_index=True,
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True, null=True)),
                (
                    "import_existing_groups",
                    models.BooleanField(
                        default=True,
                        help_text="Import existing Splitwise groups on first sync",
                    ),
                ),
                (
                    "import_existing_expenses",
                    models.BooleanField(
                        default=True,
                        help_text="Import existing expenses from Splitwise groups",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splitwise_integration",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Splitwise Integration",
                "verbose_name_plural": "Splitwise Integrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SplitwiseGroupMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("splitwise_group_id", models.IntegerField(db_index=True)),
                ("splitwise_group_name", models.CharField(max_length=255)),
                ("sync_enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("bidirectional", "Bi-directional"),
                            ("to_splitwise", "To Splitwise Only"),
                            ("from_splitwise", "From Splitwise Only"),
                        ],
                        default="bidirectional",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_splitwise_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_mappings",
                        to="services.splitwiseintegration",
                    ),
                ),
                (
                    "local_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splitwise_mapping",
                        to="finance.expensegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Splitwise Group Mapping",
                "verbose_name_plural": "Splitwise Group Mappings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SplitwiseExpenseMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("splitwise_expense_id", models.IntegerField(db_index=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_splitwise_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("pending", "Pending Sync"),
                            ("error", "Sync Error"),
                        ],
                        db_index=True,
                        default="synced",
                        max_length=20,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_mappings",
                        to="services.splitwisegroupmapping",
                    ),
                ),
                (
                    "local_expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splitwise_mapping",
                        to="finance.groupexpense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Splitwise Expense Mapping",
                "verbose_name_plural": "Splitwise Expense Mappings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this account", max_length=100
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("access_token", models.CharField(max_length=500)),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_synced_history_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "transaction_tag",
                    models.CharField(default="email-import", max_length=50),
                ),
                ("sender_filters", models.JSONField(blank=True, default=list)),
                ("keyword_filters", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gmail_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gmail Account",
                "verbose_name_plural": "Gmail Accounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailAccountPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email sender address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "sender_domain",
                    models.CharField(
                        blank=True,
                        help_text="Email domain (e.g., sbi.co.in)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "merchant_name",
                    models.CharField(
                        blank=True,
                        help_text="Merchant name pattern",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(
                        blank=True,
                        help_text="Bank/institution name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "last_digits",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits of account/card",
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "upi_id",
                    models.CharField(
                        blank=True,
                        help_text="UPI identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "wallet_name",
                    models.CharField(
                        blank=True,
                        help_text="Digital wallet name",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Confidence in this pattern (0.0-1.0)",
                        max_digits=3,
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of times this pattern has been successfully used",
                    ),
                ),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                (
                    "pattern_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full extracted pattern data from the original email",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_patterns",
                        to="finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_account_patterns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Account Pattern",
                "verbose_name_plural": "Email Account Patterns",
            },
        ),
        migrations.CreateModel(
            name="SplitwiseSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full_import", "Full Import"),
                            ("incremental", "Incremental Sync"),
                            ("push", "Push to Splitwise"),
                            ("pull", "Pull from Splitwise"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("groups_synced", models.IntegerField(default=0)),
                ("expenses_synced", models.IntegerField(default=0)),
                ("groups_created", models.IntegerField(default=0)),
                ("expenses_created", models.IntegerField(default=0)),
                ("groups_updated", models.IntegerField(default=0)),
                ("expenses_updated", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="services.splitwiseintegration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Splitwise Sync Log",
                "verbose_name_plural": "Splitwise Sync Logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["integration", "status"],
                        name="services_sp_integra_001491_idx",
                    ),
                    models.Index(
                        fields=["sync_type", "started_at"],
                        name="services_sp_sync_ty_fbf40d_idx",
                    ),
                    models.Index(
                        fields=["status", "started_at"],
                        name="services_sp_status_3b0ce0_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="splitwiseintegration",
            index=models.Index(
                fields=["is_active", "auto_sync_enabled"],
                name="services_sp_is_acti_204890_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="splitwiseintegration",
            index=models.Index(
                fields=["sync_status", "last_sync_at"],
                name="services_sp_sync_st_8a4c6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="splitwisegroupmapping",
            index=models.Index(
                fields=["integration", "sync_enabled"],
                name="services_sp_integra_36203c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="splitwisegroupmapping",
            index=models.Index(
                fields=["splitwise_group_id"], name="services_sp_splitwi_c5bf79_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="splitwisegroupmapping",
            unique_together={
                ("integration", "local_group"),
                ("integration", "splitwise_group_id"),
            },
        ),
        migrations.AddIndex(
            model_name="splitwiseexpensemapping",
            index=models.Index(
                fields=["group_mapping", "sync_status"],
                name="services_sp_group_m_860b16_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="splitwiseexpensemapping",
            index=models.Index(
                fields=["splitwise_expense_id"], name="services_sp_splitwi_dfb910_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="splitwiseexpensemapping",
            unique_together={
                ("group_mapping", "splitwise_expense_id"),
                ("group_mapping", "local_expense"),
            },
        ),
        migrations.AddIndex(
            model_name="gmailaccount",
            index=models.Index(
                fields=["user", "is_active"], name="services_gm_user_id_3e6a45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gmailaccount",
            index=models.Index(fields=["email"], name="services_gm_email_a9aa1f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="gmailaccount",
            unique_together={("user", "email")},
        ),
        migrations.AddIndex(
            model_name="emailaccountpattern",
            index=models.Index(
                fields=["user", "sender_domain"], name="services_em_user_id_b9313b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailaccountpattern",
            index=models.Index(
                fields=["user", "merchant_name"], name="services_em_user_id_c53eca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailaccountpattern",
            index=models.Index(
                fields=["user", "last_digits"], name="services_em_user_id_3d8ae3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailaccountpattern",
            index=models.Index(
                fields=["user", "institution_name"],
                name="services_em_user_id_335b23_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailaccountpattern",
            index=models.Index(
                fields=["confidence_score"], name="services_em_confide_c03bf0_idx"
            ),
        ),
    ]
