# Generated by Django 4.2.24 on 2025-11-09 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import training.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gmail", "Gmail"),
                            ("sms", "SMS"),
                            ("manual", "Manual Upload"),
                        ],
                        db_index=True,
                        default="gmail",
                        help_text="Origin of the raw payload",
                        max_length=20,
                    ),
                ),
                ("headers", models.JSONField(default=dict)),
                ("subject", models.CharField(max_length=1000)),
                ("sender", models.CharField(max_length=1000)),
                (
                    "snippet",
                    models.CharField(
                        blank=True,
                        help_text="Short preview of the message body for quick triage",
                        max_length=2048,
                    ),
                ),
                ("body_text", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                (
                    "gmail_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full Gmail payload stored for downstream training",
                    ),
                ),
                ("received_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_attempts", models.PositiveIntegerField(default=0)),
                (
                    "last_processing_attempt",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("processing_error", models.TextField(blank=True, null=True)),
                (
                    "processing_events",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Timeline of processing events",
                    ),
                ),
                (
                    "ingestion_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Raw ingestion events (fetch, manual upload, etc.)",
                    ),
                ),
                (
                    "linked_transaction_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of transaction IDs generated from this payload",
                    ),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached parsed data from email_parser",
                    ),
                ),
                (
                    "is_transaction_email",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this email contains transaction information",
                    ),
                ),
                (
                    "user_feedback",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User confirmations or edits for downstream training",
                    ),
                ),
                (
                    "attachments_ready",
                    models.BooleanField(
                        default=False,
                        help_text="True when attachments (if any) have been persisted",
                    ),
                ),
                (
                    "gmail_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_emails",
                        to="services.gmailaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Email",
                "verbose_name_plural": "Raw Emails",
                "ordering": ["-received_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Dataset name/version", max_length=255),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Semantic version (e.g., v1.0.0)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this dataset version"
                    ),
                ),
                ("total_samples", models.IntegerField(default=0)),
                ("transaction_samples", models.IntegerField(default=0)),
                ("non_transaction_samples", models.IntegerField(default=0)),
                (
                    "user_verified_count",
                    models.IntegerField(
                        default=0, help_text="Number of user-verified samples"
                    ),
                ),
                (
                    "user_corrected_count",
                    models.IntegerField(
                        default=0, help_text="Number of user-corrected samples"
                    ),
                ),
                (
                    "training_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to training data file",
                        max_length=500,
                    ),
                ),
                (
                    "validation_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to validation data file",
                        max_length=500,
                    ),
                ),
                (
                    "dataset_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional dataset statistics and info",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the active training dataset",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Dataset",
                "verbose_name_plural": "Training Datasets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AILabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("TRANSACTION", "Transaction"),
                            ("OFFER", "Offer/Promotion"),
                            ("ALERT", "Alert/Notification"),
                            ("STATEMENT", "Statement"),
                            ("SPAM", "Spam"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        help_text="Primary classification of the email",
                        max_length=20,
                    ),
                ),
                (
                    "label_confidence",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        help_text="Confidence score for the label (0.0 - 1.0)",
                        max_digits=5,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DEBIT", "Debit"),
                            ("CREDIT", "Credit"),
                            ("PAYMENT", "Payment"),
                            ("REFUND", "Refund"),
                        ],
                        db_index=True,
                        help_text="Type of transaction",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Transaction amount",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Masked account number if available",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "merchant",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Merchant or payee name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Actual transaction date from email",
                        null=True,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Transaction reference ID, UTR, or order ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("GMAIL", "Gmail"),
                            ("BANK_STATEMENT", "Bank Statement"),
                            ("SMS", "SMS"),
                        ],
                        default="GMAIL",
                        help_text="Source of the transaction notification",
                        max_length=20,
                    ),
                ),
                (
                    "extraction_model",
                    models.CharField(
                        help_text="Model used for extraction (e.g., llama3.2, gpt-4)",
                        max_length=100,
                    ),
                ),
                (
                    "extraction_prompt_version",
                    models.CharField(
                        default="v1",
                        help_text="Version of the extraction prompt used",
                        max_length=50,
                    ),
                ),
                (
                    "raw_llm_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw response from LLM for debugging",
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete extracted structured data",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Time taken for AI processing in milliseconds",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_verified",
                    models.BooleanField(
                        default=False, help_text="Whether user has verified this label"
                    ),
                ),
                (
                    "user_corrected_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRANSACTION", "Transaction"),
                            ("OFFER", "Offer/Promotion"),
                            ("ALERT", "Alert/Notification"),
                            ("STATEMENT", "Statement"),
                            ("SPAM", "Spam"),
                            ("OTHER", "Other"),
                        ],
                        help_text="User-corrected label if AI was wrong",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user_corrected_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User-corrected transaction data",
                    ),
                ),
                (
                    "raw_email",
                    models.OneToOneField(
                        help_text="Reference to the raw email being labeled",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_label",
                        to="training.rawemail",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Label",
                "verbose_name_plural": "AI Labels",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnifiedTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("DEBIT", "Debit"),
                            ("CREDIT", "Credit"),
                            ("PAYMENT", "Payment"),
                            ("REFUND", "Refund"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Primary transaction amount",
                        max_digits=15,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "merchant",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized merchant name",
                        max_length=255,
                    ),
                ),
                (
                    "merchant_variants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Different merchant name variations found across sources",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Account number (masked)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "reference_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="All reference IDs from merged sources",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        db_index=True, help_text="Primary transaction date"
                    ),
                ),
                (
                    "primary_source",
                    models.CharField(
                        choices=[
                            ("GMAIL", "Gmail"),
                            ("BANK_STATEMENT", "Bank Statement"),
                            ("SMS", "SMS"),
                        ],
                        help_text="Primary source of this transaction",
                        max_length=20,
                    ),
                ),
                (
                    "merge_confidence",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        help_text="Confidence in the merge decision (0.0 - 1.0)",
                        max_digits=5,
                    ),
                ),
                (
                    "merge_reason",
                    models.TextField(
                        blank=True, help_text="Explanation of why sources were merged"
                    ),
                ),
                (
                    "merge_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed merge algorithm output",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Transaction description from sources"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Auto-categorized transaction category",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has verified this transaction",
                    ),
                ),
                (
                    "user_edited",
                    models.BooleanField(
                        default=False, help_text="Whether user has edited any fields"
                    ),
                ),
                (
                    "is_duplicate",
                    models.BooleanField(
                        default=False, help_text="Marked as duplicate by user or system"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_ai_labels",
                    models.ManyToManyField(
                        help_text="All AI labels that contributed to this unified transaction",
                        related_name="unified_transactions",
                        to="training.ailabel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unified_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unified Transaction",
                "verbose_name_plural": "Unified Transactions",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "transaction_date"],
                        name="training_un_user_id_2c3c5e_idx",
                    ),
                    models.Index(
                        fields=["user", "merchant"],
                        name="training_un_user_id_2edd19_idx",
                    ),
                    models.Index(
                        fields=["user", "transaction_type"],
                        name="training_un_user_id_987d0b_idx",
                    ),
                    models.Index(
                        fields=["transaction_date", "amount"],
                        name="training_un_transac_e2df2a_idx",
                    ),
                    models.Index(
                        fields=["merchant", "transaction_date"],
                        name="training_un_merchan_30b175_idx",
                    ),
                    models.Index(
                        fields=["user", "is_duplicate"],
                        name="training_un_user_id_41064e_idx",
                    ),
                    models.Index(
                        fields=["merge_confidence"],
                        name="training_un_merge_c_65bed1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RawEmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=512)),
                ("mime_type", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveIntegerField(default=0)),
                (
                    "file",
                    models.FileField(
                        upload_to=training.models.raw_email_attachment_upload_to
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="training.rawemail",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["raw_email", "filename"],
                        name="training_ra_raw_ema_72e600_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="rawemail",
            index=models.Index(
                fields=["user", "processing_status"],
                name="training_ra_user_id_981a92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawemail",
            index=models.Index(
                fields=["user", "received_at"], name="training_ra_user_id_d9b233_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawemail",
            index=models.Index(
                fields=["gmail_account", "processing_status"],
                name="training_ra_gmail_a_ad36bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawemail",
            index=models.Index(
                fields=["sender", "received_at"], name="training_ra_sender_d585c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawemail",
            index=models.Index(
                fields=["is_transaction_email", "processing_status"],
                name="training_ra_is_tran_34de33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawemail",
            index=models.Index(
                fields=["processing_status", "created_at"],
                name="training_ra_process_b68187_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawemail",
            index=models.Index(
                fields=["user", "source", "processing_status"],
                name="training_ra_user_id_b84dc6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ailabel",
            index=models.Index(
                fields=["label", "label_confidence"],
                name="training_ai_label_aacd0b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ailabel",
            index=models.Index(
                fields=["transaction_type", "transaction_date"],
                name="training_ai_transac_754045_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ailabel",
            index=models.Index(
                fields=["merchant", "amount"], name="training_ai_merchan_04f611_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ailabel",
            index=models.Index(
                fields=["reference_id"], name="training_ai_referen_0e5690_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ailabel",
            index=models.Index(
                fields=["transaction_date", "amount"],
                name="training_ai_transac_b01cc5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ailabel",
            index=models.Index(
                fields=["user_verified"], name="training_ai_user_ve_376fd3_idx"
            ),
        ),
    ]
