# Generated by Django 4.2.24 on 2025-11-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 3166-1 alpha-2 country code (e.g., US, GB, IN)",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the country", max_length=100
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        blank=True, help_text="Unicode flag emoji", max_length=10
                    ),
                ),
                (
                    "dial_code",
                    models.CharField(
                        blank=True,
                        help_text="International dialing code (e.g., +1, +44, +91)",
                        max_length=10,
                    ),
                ),
                (
                    "default_timezone",
                    models.CharField(
                        blank=True,
                        help_text="Default timezone for this country (e.g., America/New_York)",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this country is active and can be selected",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default currency for this country",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="countries",
                        to="finance.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 639-1 language code (e.g., en, es, hi)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the language in English", max_length=100
                    ),
                ),
                (
                    "native_name",
                    models.CharField(
                        help_text="Name of the language in its native script",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this language is active and can be selected",
                    ),
                ),
                (
                    "is_rtl",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this language is written right-to-left",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Timezone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="IANA timezone name (e.g., America/New_York, Europe/London)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label for the timezone", max_length=100
                    ),
                ),
                (
                    "offset",
                    models.CharField(
                        help_text="UTC offset (e.g., UTC-5, UTC+5:30)", max_length=10
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, help_text="Associated country code", max_length=2
                    ),
                ),
                (
                    "is_common",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a commonly used timezone",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this timezone is active and can be selected",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Timezone",
                "verbose_name_plural": "Timezones",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="LocaleMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "locale_code",
                    models.CharField(
                        db_index=True,
                        help_text="Locale code (e.g., en-US, en-GB, hi-IN)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this locale mapping is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated country",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locales",
                        to="reference.country",
                    ),
                ),
                (
                    "default_currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default currency for this locale",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locales",
                        to="finance.currency",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated language",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locales",
                        to="reference.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Locale Mapping",
                "verbose_name_plural": "Locale Mappings",
                "ordering": ["locale_code"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol_native",
                    models.CharField(help_text="Native currency symbol", max_length=10),
                ),
                (
                    "name_plural",
                    models.CharField(
                        help_text="Plural name of the currency", max_length=100
                    ),
                ),
                (
                    "rounding",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rounding precision",
                        max_digits=10,
                    ),
                ),
                (
                    "space_between_amount_and_symbol",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to add space between amount and symbol",
                    ),
                ),
                (
                    "is_common",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a commonly used currency",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.OneToOneField(
                        help_text="Associated currency",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="finance.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency Info",
                "verbose_name_plural": "Currency Info",
            },
        ),
    ]
