# Generated by Django 4.2.24 on 2025-11-09 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance_v2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("merchant", "Merchant"),
                            ("person", "Person"),
                            ("company", "Company"),
                            ("bank", "Bank"),
                            ("government", "Government"),
                            ("other", "Other"),
                        ],
                        default="merchant",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("currency", models.CharField(max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groups_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_owed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="finance_v2.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["group", "user"],
            },
        ),
        migrations.CreateModel(
            name="StatementPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encrypted_password",
                    models.BinaryField(help_text="Fernet encrypted password"),
                ),
                ("password_hint", models.CharField(blank=True, max_length=255)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default password to try first"
                    ),
                ),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("success_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_passwords",
                        to="finance.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_passwords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "finance_statement_passwords",
                "ordering": ["-is_default", "-success_count"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_expense", models.BooleanField()),
                ("description", models.CharField(blank=True, max_length=500)),
                ("date", models.DateField()),
                (
                    "expense_classification",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("charity", "Charity"),
                            ("family", "Family Support"),
                            ("reimbursable", "Reimbursable"),
                            ("one_time", "One-time"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("exclude_from_totals", models.BooleanField(default=False)),
                ("chat_metadata", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions_v2",
                        to="finance.account",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance_v2.entity",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance_v2.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=finance_v2.models.uploaded_file_path),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("statement", "Bank Statement"),
                            ("receipt", "Receipt"),
                            ("invoice", "Invoice"),
                            ("bill", "Bill"),
                            ("document", "Other Document"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "processing_mode",
                    models.CharField(
                        choices=[
                            ("parser", "Deterministic Parser"),
                            ("ai", "AI Parser"),
                        ],
                        default="parser",
                        help_text="Select AI-driven parsing or the deterministic parser",
                        max_length=20,
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ocr_text", models.TextField(blank=True)),
                ("is_password_protected", models.BooleanField(default=False)),
                (
                    "raw_text",
                    models.TextField(
                        blank=True, help_text="Raw extracted text for comparison"
                    ),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True, help_text="Structured parsed data", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "used_password",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unlocked_files",
                        to="finance_v2.statementpassword",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "split_method",
                    models.CharField(
                        choices=[
                            ("equal", "Equal"),
                            ("percentage", "Percentage"),
                            ("amount", "Amount"),
                            ("shares", "Shares"),
                        ],
                        default="equal",
                        max_length=20,
                    ),
                ),
                (
                    "split_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Percentage (e.g., 33.33) or shares (e.g., 2)",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="finance_v2.groupmember",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="finance_v2.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["transaction", "member"],
            },
        ),
        migrations.CreateModel(
            name="TransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=15
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance_v2.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["transaction", "name"],
            },
        ),
        migrations.CreateModel(
            name="PendingTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("file", "Uploaded File"),
                            ("manual", "Manual Entry"),
                            ("api", "API Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_expense", models.BooleanField()),
                ("description", models.CharField(blank=True, max_length=500)),
                ("date", models.DateField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("items", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("merged", "Merged with Another"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_transactions",
                        to="finance_v2.entity",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_transactions",
                        to="finance_v2.group",
                    ),
                ),
                (
                    "imported_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_sources",
                        to="finance_v2.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_transactions_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        db_index=True,
                        default="main",
                        help_text="Group messages by conversation",
                        max_length=255,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("system", "System"),
                            ("suggestion", "Suggestion"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Parsed data, mentions, AI confidence, etc.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="finance_v2.uploadedfile",
                    ),
                ),
                (
                    "related_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="finance_v2.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "finance_chat_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["file_type"], name="finance_v2__file_ty_81a743_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["file_hash"], name="finance_v2__file_ha_559e8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="finance_v2__content_3419e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["created_at"], name="finance_v2__created_44eb1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionsplit",
            index=models.Index(
                fields=["transaction"], name="finance_v2__transac_7a730d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transactionsplit",
            unique_together={("transaction", "member")},
        ),
        migrations.AddIndex(
            model_name="transactionitem",
            index=models.Index(
                fields=["transaction"], name="finance_v2__transac_8b88c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "date", "-created_at"],
                name="finance_v2__user_id_c3c9d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "is_expense", "date"],
                name="finance_v2__user_id_68f4af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "is_deleted"], name="finance_v2__user_id_4931e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["group"], name="finance_v2__group_i_1d3f5d_idx"),
        ),
        migrations.AddIndex(
            model_name="statementpassword",
            index=models.Index(
                fields=["user", "account"], name="finance_sta_user_id_b8f236_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingtransaction",
            index=models.Index(
                fields=["user", "status"], name="finance_v2__user_id_7b0767_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingtransaction",
            index=models.Index(
                fields=["source", "source_id"], name="finance_v2__source_412a38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pendingtransaction",
            index=models.Index(fields=["date"], name="finance_v2__date_a4dd8d_idx"),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(fields=["group"], name="finance_v2__group_i_a36a27_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together={("group", "user")},
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["created_by", "is_active"],
                name="finance_v2__created_ddcbab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["user", "entity_type"], name="finance_v2__user_id_f1adf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entity",
            index=models.Index(
                fields=["user", "is_active"], name="finance_v2__user_id_fc8959_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["user", "conversation_id", "-created_at"],
                name="finance_cha_user_id_e4b8c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["user", "status"], name="finance_cha_user_id_c393e0_idx"
            ),
        ),
    ]
