# Generated by Django 4.2.24 on 2025-11-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisettings",
            name="gemini_api_key",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="gemini_model",
            field=models.CharField(blank=True, default="gemini-pro", max_length=50),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="chat_mode",
            field=models.CharField(
                choices=[("normal", "Normal"), ("ai", "AI"), ("shortcut", "Shortcut")],
                default="ai",
                help_text="Chat interface mode",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sidebar_collapsed",
            field=models.BooleanField(
                default=False, help_text="Whether sidebar is collapsed by default"
            ),
        ),
        migrations.AlterField(
            model_name="aisettings",
            name="preferred_provider",
            field=models.CharField(
                choices=[
                    ("system", "System Default"),
                    ("openai", "OpenAI"),
                    ("ollama", "Ollama"),
                    ("anthropic", "Anthropic"),
                    ("gemini", "Google Gemini"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
